name: Build and Push Docker Image

on:
  push:
    branches:
      - deploy
    paths:
      - '**/*.java'
      - '**/build.gradle'
      - 'Dockerfile'
      - 'helm-charts/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set service name from directory
        id: vars
        run: echo "SERVICE_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Find built JAR
        id: find_jar
        run: |
          JAR_PATH=$(find build/libs -type f -name '*SNAPSHOT.jar' ! -name '*plain.jar' | head -n 1)
          echo "jar_path=$JAR_PATH" >> "$GITHUB_OUTPUT"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build --build-arg JAR_FILE=${{ steps.find_jar.outputs.jar_path }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/$SERVICE_NAME:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$SERVICE_NAME:latest
